---
# handlers file for roles/wordpress

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
    
- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart php-fpm
  systemd:
    name: php-fpm
    state: restarted
    enabled: yes
