---
# handlers file for roles/ospf

- name: reload eth0
  shell: "ifdown eth0 && ifup eth0"

- name: restart zebra service
  systemd:
    name: zebra
    state: restarted
    enabled: yes

- name: restart ospfd service
  systemd:
    name: ospfd
    state: restarted
    enabled: yes