web:
    image: somikhaylov/nginx:1.0
    ports:
        - "80:80"
    volumes:
        - ./site:/site
        - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    links: 
        - php
php:
    image: somikhaylov/php-fpm:1.0
    volumes:
        - ./conf/php-fpm.conf:/etc/php7/php-fpm.conf
        - ./site:/site