interfaces:
  team:
    - name: team0
      ipaddr: 192.168.255.1
      netmask: 255.255.255.252
  team_slave:
    - name: eth1
      master: team0
    - name: eth2
      master: team0

rules:
  - dst: "! 192.168.0.0/16"
    dev: eth0

routes:
  - subnet: 192.168.10.0/24
    gw: 192.168.255.2