---
# tasks file for roles/nginx

- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install nginx
  yum:
    name: nginx
    state: present

- name: create directory for web
  file:
    path: /var/www/html/
    state: directory
    mode: 0755 

- name: copy nginx-wordpress.conf
  copy:
    src: nginx-wordpress.conf
    dest: /etc/nginx/conf.d/wordpress.conf
  notify: restart nginx

- name: copy nginx-kibana.conf
  copy:
    src: nginx-kibana.conf
    dest: /etc/nginx/conf.d/kibana.conf
  notify: restart nginx

- name: copy nginx-grafana.conf
  copy:
    src: nginx-grafana.conf
    dest: /etc/nginx/conf.d/grafana.conf
  notify: restart nginx
  