---
- name: Install ipa-client
  hosts: client    
  become: true
  tasks:
    - name: set FQDN hostname 
      hostname:
        name: client.example.com
    
    - name: update nss package
      yum:
        name: nss
        state: latest

    - name: Install ipa-client package
      yum:
        name: freeipa-client
        state: present

    - name: Setup ipa-client
      command:  >
        ipa-client-install
        --mkhomedir
        --server=server.example.com
        --realm=EXAMPLE.COM
        --domain=example.com
        --hostname=client.example.com
        --password=password
        --principal=admin
        --unattended
