---
# tasks file for roles/pgsql

- name: Update hosts file
  lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items:
    - "192.168.1.100 master"
    - "192.168.1.200 slave"
    - "192.168.1.150 backup"
    
- name: install epel-release
  yum: 
    name: epel-release
    state: present

- name: check postgresql repo
  stat:
    path: /etc/yum.repos.d/pgdg-redhat-all.repo
  register: pgsql_repo

- name: install pgsql repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  when: not pgsql_repo.stat.exists

- name: Exclude barman from PostgreSQL repo
  lineinfile:
    path: /etc/yum.repos.d/pgdg-redhat-all.repo
    line: exclude=barman*
    state: present

- name: check barman repo
  stat:
    path: /etc/yum.repos.d/2ndquadrant-dl-default-release-pg9.6.repo 
  register: barman_repo

- name: Install Barman repo
  shell: curl https://dl.2ndquadrant.com/default/release/get/9.6/rpm | sudo bash
  when: not barman_repo.stat.exists

- name: install packages
  yum:
    name: 
      - postgresql96-server
      - postgresql96
      - barman
      - barman-cli
      - unzip
      - python-pip
      - postgresql-libs
      - python-psycopg2
    state: present

- name: install pip packages
  pip:
    name: psycopg2-binary
    state: present

- name: Disable SELinux
  selinux:
    state: disabled


- name: check if pgsql db is initialized.
  stat:
    path: /var/lib/pgsql/9.6/data/PG_VERSION
  register: pgdata_dir_version

- name: initialized pgsql db
  shell: /usr/pgsql-9.6/bin/postgresql96-setup initdb
  when: not pgdata_dir_version.stat.exists

- name: start postgresql service
  systemd:
    name: postgresql-9.6
    state: started
    enabled: yes

# repl
- name: create user replication
  become_user: postgres
  postgresql_user:
    db: postgres
    name: replication
    password: Password1!
    role_attr_flags: REPLICATION,LOGIN

- name: create user for backup
  become_user: postgres
  postgresql_user:
    db: postgres
    name: barman
    password: Password1!
    role_attr_flags: SUPERUSER

- name: create directory .ssh
  file:
    path: /var/lib/pgsql/.ssh
    state: directory
    group: postgres
    owner: postgres
    mode: 0700

- name: copy keys
  copy:
    src: keys/
    dest: /var/lib/pgsql/.ssh
    group: postgres
    owner: postgres

- name: copy conf on master
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: postgres
    group: postgres
  when: 
    - conf is defined
    - type is defined and type == "master"
  with_items: '{{ conf }}'

- name: restart postgresql service
  systemd:
    name: postgresql-9.6
    state: restarted
    enabled: yes

- name: stop pgsql service on slave
  systemd:
    name: postgresql-9.6
    state: stopped
  when: type is defined and type == "slave"

- name: remove pgdata directory on slave
  file:
    path: /var/lib/pgsql/9.6/data
    state: absent
  when: type is defined and type == "slave"

- name: copy db from master to slave
  become_user: postgres
  shell: pg_basebackup -h master -D /var/lib/pgsql/9.6/data/ -R -P -U replication
  when: type is defined and type == "slave"

- name: start pgsql service on slave
  systemd:
    name: postgresql-9.6
    state: started
  when: type is defined and type == "slave"

# backup

- name: Create directory .ssh barman
  file:
    path: /var/lib/barman/.ssh
    state: directory
    group: barman
    owner: barman

- name: copy keys barman
  copy:
    src: keys/
    dest: /var/lib/barman/.ssh
    group: barman
    owner: barman
    mode: 0600

- name: copy barman conf
  copy:
    src: barman.conf
    dest: /etc/barman.conf
  when: type is defined and type == "backup"
