---
# tasks file for roles/pgsql

- name: install packages
  dnf:
    name: 
      - '@postgresql:9.6'
      - unzip
    state: present

- name: check if pgsql db is initialized.
  stat:
    path: /var/lib/pgsql/data/PG_VERSION
  register: pgdata_dir_version

- name: initialized pgsql db
  shell: postgresql-setup --initdb
  when: not pgdata_dir_version.stat.exists

- name: start postgresql service
  systemd:
    name: postgresql
    state: started
    enabled: yes

- name: download demo database from postgrespro.ru
  unarchive:
    src: https://edu.postgrespro.ru/demo-small-20161013.zip
    dest: /tmp
    remote_src: yes


- name: load demo db
  postgresql_query:
    path_to_script: /tmp/demo_small.sql
